---
- name: Install android tools
  apt:
    pkg: "{{ item }}"
  with_items:
    - android-tools-adb
    - android-tools-fastboot
  when: ansible_os_family == "Debian"


- name: install udev rules
  copy:
    src: etc/udev/rules.d/51-android.rules
    dest: /etc/udev/rules.d/51-android.rules
    owner: root
    group: root
    mode: 0644
  notify: restart udev
